### ISSUE TITLE
Doesnt build on Ubuntu 18.04

### ISSUE THREAD

**Issue by Jimbles** [EIT-team/PEITS#11]
Fails when running `sh INSTALL` with the following error
```
/usr/include/c++/7/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
```
Its probably related to the newer GCC, there are so many places where build and compiler flags are set that I am unsure where to set `-std=c++11 or -std=gnu++11 `

**Comment by ca-ja** [comment]
Dear Jimbles,
Have you overcome this issue yet?
Thank you in advance.

**Comment by Jimbles** [comment]
Hey,
Im afraid not, I had to get back to some real work so I havent had a chance to look into this again. it looks like you might be able to add it to `configure.ac` like [here](https://unix.stackexchange.com/questions/241328/autoconf-setting-compiler-flags-for-checks) but i havent got round to checking it yet.
How would you like to use PEITS?

**Comment by ca-ja** [comment]
I am playing with a utilization of EIT for structural health monitoring.
Thanks to your contribution in thread "Doesn't build on Ubuntu 16.x" I am running PEITS on Ubuntu 16.04 currently.
So, great thanks.

**Comment by Jimbles** [comment]
Oh good, I'm glad you got it working. Please let know how you get on using it!

**Comment by RolandMacDoland** [comment]
Looking to build in my Ubuntu18 VM.

**Comment by RolandMacDoland** [comment]
As a matter of fact, @Jimbles , is there any reason for being bounded to any particular dependency version ? Would it make sense to try the ones that come natively with Ubuntu18 ?

**Comment by RolandMacDoland** [comment]
Thinking of gcc8, gfortran8, newer versions of MPI etc...

**Comment by tdowrick** [comment]
Agreed that it would be better to try and get it to work with the native Ubuntu libraries - I don't think there is any reason not to.

**Comment by RolandMacDoland** [comment]
OK, I am trying to install it with the above versions to see if that is working. If I get a successful install, I'll see with the native Ubuntu18 libs.

**Comment by Jimbles** [comment]
I agree! Native libraries is much better, I think I was looking for a hack, as if there were anything more involved about changing the code to work with 18.04 I wouldnt be equipped to do
